---@class StoreModalConfig : PluginConfig
---@field on_close? fun(): void Callback when modal is closed

---@class StoreModalState
---@field filter_query string
---@field sort_config { type: string }
---@field repos Repository[]
---@field currently_displayed_repos Repository[]
---@field total_installed_count integer
---@field installed_items table<string, boolean>
---@field install_catalogue table<string, string>|nil
---@field install_catalogue_manager string|nil
---@field plugin_manager_mode string
---@field plugin_manager_overview table<string, { count: integer, status: string, error: string|nil }>
---@field current_focus number|nil
---@field current_repository Repository|nil
---@field is_closing boolean
---@field autocmds integer[]

---@class StoreModal
---@field config StoreModalConfig Complete computed configuration
---@field state StoreModalState Mutable modal state
---@field heading Heading Header component instance
---@field list List List component instance
---@field preview Preview Preview component instance
---@field open fun(self: StoreModal): string|nil
---@field close fun(self: StoreModal): string|nil
